# Generated by Django 3.2.25 on 2024-06-29 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(verbose_name='Url-Адрес')),
                ('bitlink', models.URLField(blank=True, null=True, verbose_name='Сокращенная ссылка')),
                ('clicks', models.IntegerField(default=0, verbose_name='Количество переходов')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_storage', models.DateField(verbose_name='начало хранения')),
                ('end_storage', models.DateField(verbose_name='конец хранения')),
                ('size', models.PositiveIntegerField(blank=True, null=True, verbose_name='кв.м')),
                ('status', models.CharField(choices=[('reserved', 'зарезервирован'), ('in_storage', 'на хранении'), ('removed', 'снят с хранения'), ('expired', 'просрочен')], default='reserved', max_length=10, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Боксы',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone', models.IntegerField(unique=True, verbose_name='телефон')),
                ('telegram_id', models.CharField(max_length=50, verbose_name='телеграмм ID')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('address', models.TextField(verbose_name='адрес')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='цена')),
                ('state', models.CharField(choices=[('todo', 'принять в работу'), ('true', 'подтвержден'), ('topay', 'выставить счет'), ('false', 'отменен')], default='todo', max_length=9, verbose_name='состояние')),
                ('box', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_models.box')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stock_models.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='box',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='stock_models.client', verbose_name='клиент'),
        ),
    ]
