# Generated by Django 3.2.25 on 2024-06-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Телефон'),
        ),
    ]
