# Generated by Django 3.2.25 on 2024-06-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('bitlink', models.URLField(blank=True, null=True)),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
