# Generated by Django 3.2.25 on 2024-06-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0002_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='end_storage',
            field=models.DateTimeField(verbose_name='конец хранения'),
        ),
        migrations.AlterField(
            model_name='box',
            name='start_storage',
            field=models.DateTimeField(verbose_name='начало хранения'),
        ),
    ]
