# Generated by Django 3.2.25 on 2024-07-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0003_auto_20240701_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='end_storage',
            field=models.DateField(verbose_name='конец хранения'),
        ),
        migrations.AlterField(
            model_name='box',
            name='start_storage',
            field=models.DateField(verbose_name='начало хранения'),
        ),
    ]
